#!/bin/sh
cd "${0%/*}" || exit

for d in solidBodyDisplacementLaplacianZone dynamicOversetMotionSolverFvMesh fsiOmega precice-openfoam-adapter
 do
    echo ""
    echo "=== Cleaning $d ==="
    (cd "$d" && ./Allclean "$@") || exit $?
 done

echo ""
echo "All plugins cleaned successfully."
