#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the blade (and hub) element data for the NREL Phase VI case.

Reads the committed geometry `data/geometry/phaseVI_blade.csv` (NREL/TP-500-29955
Table A-1) and emits turbinesFoam element data rows

    (axialDistance radius azimuth chord chordMount pitch)

with the `-(twist + pitch)` mounting convention. The same rows are embedded in
the generated `system/fvOptions.ALM|ASM`; this script exposes them standalone
and validates the configured kinematics first (tip-displacement constraint,
measured TSR against the committed experimental rows).

Usage:
    makeElementData.py [--config PATH] [--output PATH] [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "tools"))

from case_config import (  # noqa: E402
    DEFAULT_CONFIG,
    assert_tip_constraint,
    assert_tsr_matches_experiment,
    load_config,
    speed_keys,
)
from element_data import (  # noqa: E402
    HUB_DIAMETER,
    blade_element_rows,
    element_data_summary,
    hub_element_rows,
)


def render(cfg) -> str:
    header = (
        "// Blade and hub element data generated by scripts/makeElementData.py\n"
        "// from data/geometry/phaseVI_blade.csv (NREL/TP-500-29955 Table A-1).\n"
        "// columns: axialDistance radius azimuth chord chordMount pitch\n"
        "// Mounting angle: pitch = -(twist + pitch_deg), pitch_deg = 3.\n"
    )
    lines = [header, "blade1", "("]
    for row in blade_element_rows(cfg):
        lines.append("    (" + " ".join(f"{value:.9g}" for value in row) + ")")
    lines.append(");")
    lines.append("")
    lines.append("hub")
    lines.append("(")
    for row in hub_element_rows():
        lines.append("    (" + " ".join(f"{value:.9g}" for value in row) + ")")
    lines.append(");")
    return "\n".join(lines) + "\n"


def validate(cfg) -> None:
    for speed in speed_keys(cfg):
        for mesh in sorted(cfg["mesh"]["resolutions"]):
            assert_tip_constraint(cfg, speed, mesh)
    assert_tsr_matches_experiment(cfg)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="write the element data to this path instead of stdout",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail (exit 1) when --output is missing or stale; never writes",
    )
    args = parser.parse_args(argv)

    cfg = load_config(args.config)
    validate(cfg)
    content = render(cfg)
    summary = element_data_summary(cfg)
    print(
        "element data: "
        f"{summary['stations']} blade stations "
        f"({summary['root_radius']:.4g} m .. {summary['tip_radius']:.4g} m), "
        f"hub diameter {HUB_DIAMETER:.4g} m, "
        f"root mounting {summary['root_mounting_deg']:.4g} deg, "
        f"tip mounting {summary['tip_mounting_deg']:.4g} deg",
        file=sys.stderr,
    )

    if args.check:
        if args.output is None:
            parser.error("--check requires --output")
        if not args.output.exists():
            print(f"missing element data: {args.output}", file=sys.stderr)
            return 1
        if args.output.read_text(encoding="utf-8") != content:
            print(f"stale element data: {args.output}", file=sys.stderr)
            return 1
        return 0

    if args.output is None:
        print(content, end="")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(content, encoding="utf-8")
        print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
